Repository nf-core/phaseimpute, pull requests merged in 2024-10, with the labels that each got.

#134 Add animated metro map
  README.md
  docs/images/metro/MetroMap.png
  docs/images/metro/MetroMap.svg
  docs/images/metro/MetroMap.xml
  docs/images/metro/legend.png
  docs/images/metro/txt2image.md
Labels: documentation

#143 Fix checkchr
  CHANGELOG.md
  modules.json
  modules/local/add_columns/environment.yml
  modules/local/bam_chr_extract/environment.yml
  modules/local/list_to_file/environment.yml
  modules/local/vcf_chr_extract/environment.yml
  nextflow.config
  nextflow_schema.json
  subworkflows/local/utils_nfcore_chrcheck_pipeline/main.nf
  subworkflows/local/utils_nfcore_phaseimpute_pipeline/main.nf
  subworkflows/nf-core/utils_nfschema_plugin/tests/main.nf.test
  workflows/chrcheck/main.nf
  workflows/chrcheck/tests/main.nf.test
  workflows/chrcheck/tests/main.nf.test.snap
  workflows/chrcheck/tests/nextflow.config
  workflows/chrcheck/tests/nextflow_rename.config
Labels: enhancement

#146 Conda check removed and seed parameters added for QUILT
  .github/workflows/ci.yml
  .nf-core.yml
  CHANGELOG.md
  conf/steps/imputation_quilt.config
  nextflow_schema.json
Labels: bug, enhancement

#144 Documentation updates
  CHANGELOG.md
  README.md
  docs/usage.md
Labels: documentation

#147 Update usage.md
  docs/usage.md
Labels: documentation

#148 Fix workflow dispatch
  .github/workflows/awsfulltest.yml
Labels: bug

#149 Remove map from awsfulltest
  conf/test_full.config
Labels: bug

#152 Fix URLs and simplify citation
  CHANGELOG.md
  CITATIONS.md
  README.md
  docs/images/InputSoftware_compatibility.png
  docs/images/metro/Impute.png
  docs/images/metro/MetroMap.png
  docs/images/metro/MetroMap.svg
  docs/images/metro/MetroMap_animated.svg
  docs/images/metro/PanelPrep.png
  docs/images/metro/Simulate.png
  docs/images/metro/Validate.png
  docs/images/metro/txt2image.md
  docs/output.md
  docs/usage.md
Labels: documentation
