Repository nf-core/phaseimpute, pull requests merged in 2024-05, with the labels that each got.

#48 Important! Template update for nf-core/tools v2.14.1
  .editorconfig
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/awsfulltest.yml
  .github/workflows/awstest.yml
  .github/workflows/ci.yml
  .github/workflows/download_pipeline.yml
  .github/workflows/fix-linting.yml
  .github/workflows/linting.yml
  .github/workflows/linting_comment.yml
  .github/workflows/release-announcements.yml
  .nf-core.yml
  .pre-commit-config.yaml
  README.md
  conf/base.config
  conf/modules.config
  conf/test.config
  conf/test_full.config
  docs/usage.md
  modules.json
  modules/nf-core/fastqc/main.nf
  nextflow.config
  nextflow_schema.json
  pyproject.toml
  subworkflows/local/utils_nfcore_phaseimpute_pipeline/main.nf
  subworkflows/nf-core/utils_nfcore_pipeline/main.nf
Labels: enhancement

#51 Update modules and fix linting
  .nf-core.yml
  CHANGELOG.md
  modules.json
  modules/nf-core/bcftools/annotate/main.nf
  modules/nf-core/bcftools/annotate/tests/bcf.config
  modules/nf-core/bcftools/annotate/tests/main.nf.test
  modules/nf-core/bcftools/annotate/tests/main.nf.test.snap
  modules/nf-core/bcftools/annotate/tests/tags.yml
  modules/nf-core/bcftools/annotate/tests/vcf.config
  modules/nf-core/bcftools/concat/main.nf
  modules/nf-core/bcftools/concat/tests/main.nf.test
  modules/nf-core/bcftools/concat/tests/main.nf.test.snap
  modules/nf-core/bcftools/mpileup/main.nf
  modules/nf-core/bcftools/mpileup/tests/main.nf.test
  modules/nf-core/bcftools/mpileup/tests/main.nf.test.snap
  modules/nf-core/fastqc/main.nf
  modules/nf-core/gawk/main.nf
  modules/nf-core/glimpse2/ligate/main.nf
  subworkflows/nf-core/vcf_phase_shapeit5/main.nf
Labels: enhancement

#47 Add new functionality (sample removal, glimpse2 chunking) and migrate to nf-schema
  CHANGELOG.md
  README.md
  conf/steps/imputation.config
  conf/steps/imputation_quilt.config
  conf/steps/panel_prep.config
  conf/test_full.config
  conf/test_glimpse2.config
  docs/output.md
  docs/usage.md
  nextflow.config
  nextflow_schema.json
  subworkflows/local/bam_impute_quilt/bam_impute_quilt.nf
  subworkflows/local/make_chunks/make_chunks.nf
  subworkflows/local/vcf_chunk_glimpse/vcf_chunk_glimpse.nf
  subworkflows/local/vcf_impute_glimpse2/main.nf
  subworkflows/local/vcf_normalize_bcftools/meta.yml
  subworkflows/local/vcf_normalize_bcftools/vcf_normalize_bcftools.nf
  subworkflows/local/vcf_sites_extract_bcftools/main.nf
  subworkflows/local/vcf_sites_extract_bcftools/meta.yml
  tests/csv/sample_sim_full.csv
  workflows/phaseimpute/main.nf
Labels: enhancement

#56 Pipeline test
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
  conf/steps/imputation_glimpse1.config
  conf/steps/imputation_glimpse2.config
  conf/steps/imputation_quilt.config
  conf/steps/imputation_stitch.config
  conf/steps/panel_prep.config
  conf/steps/simulation.config
  conf/steps/validation.config
  conf/test.config
  conf/test_glimpse2.config
  docs/development.md
  main.nf
  modules.json
  modules/local/addcolumns/main.nf
  modules/nf-core/samtools/merge/environment.yml
  modules/nf-core/samtools/merge/main.nf
  modules/nf-core/samtools/merge/meta.yml
  modules/nf-core/samtools/merge/samtools-merge.diff
  modules/nf-core/samtools/merge/tests/index.config
  modules/nf-core/samtools/merge/tests/main.nf.test
  modules/nf-core/samtools/merge/tests/main.nf.test.snap
  modules/nf-core/samtools/merge/tests/tags.yml
  nextflow.config
  nf-test.config
  subworkflows/local/bam_downsample/main.nf
  subworkflows/local/bam_gl_bcftools/main.nf
  subworkflows/local/bam_impute_quilt/main.nf
  subworkflows/local/bam_impute_stitch/main.nf
  subworkflows/local/bam_region/main.nf
  subworkflows/local/prepare_input_stitch/main.nf
  subworkflows/local/prepare_posfile_tsv/main.nf
  subworkflows/local/utils_nfcore_phaseimpute_pipeline/main.nf
  subworkflows/local/vcf_concatenate_bcftools/main.nf
  subworkflows/local/vcf_concordance_glimpse2/main.nf
  subworkflows/local/vcf_impute_glimpse1/main.nf
  subworkflows/local/vcf_impute_glimpse2/main.nf
  subworkflows/local/vcf_phase_panel/main.nf
  subworkflows/local/vcf_sites_extract_bcftools/main.nf
  tests/config/nf-test.config
  tests/test_default.yml
  workflows/phaseimpute/main.nf
  workflows/phaseimpute/tests/test_all.nf.test
  workflows/phaseimpute/tests/test_all.nf.test.snap
Labels: enhancement

#65 Separate stitch output by chromosomes
  CHANGELOG.md
  conf/steps/imputation_stitch.config
  modules.json
  modules/nf-core/bcftools/pluginsplit/bcftools-pluginsplit.diff
  modules/nf-core/bcftools/pluginsplit/environment.yml
  modules/nf-core/bcftools/pluginsplit/main.nf
  modules/nf-core/bcftools/pluginsplit/meta.yml
  modules/nf-core/stitch/main.nf
  subworkflows/local/bam_impute_stitch/main.nf
  subworkflows/local/prepare_input_stitch/main.nf
  subworkflows/local/vcf_concordance_glimpse2/main.nf
  subworkflows/local/vcf_samples_bcftools/main.nf
  workflows/phaseimpute/main.nf
  workflows/phaseimpute/tests/test_all.nf.test
  workflows/phaseimpute/tests/test_all.nf.test.snap
Labels: bug, enhancement

#66 Fix phase panel
  conf/steps/panel_prep.config
  conf/test_all.config
  conf/test_panelprep.config
  subworkflows/local/vcf_chunk_glimpse/main.nf
  subworkflows/local/vcf_concatenate_bcftools/main.nf
  subworkflows/local/vcf_phase_panel/main.nf
  subworkflows/local/vcf_phase_shapeit5/main.nf
  subworkflows/local/vcf_samples_bcftools/main.nf
  subworkflows/nf-core/vcf_phase_shapeit5/main.nf
  subworkflows/nf-core/vcf_phase_shapeit5/meta.yml
  workflows/phaseimpute/main.nf
Labels: bug
